---
title: ""
output:
  html_document:
    df_print: paged
---
# YPLL
```{r}
library(caret)
library(xgboost)
library(plyr)
library(doParallel)
library(pdp)
rm(list = ls())
set.seed (1)
load("analytic3.RData")
YPLLanalytic=analytic3[-c(2,3,4)]
nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(YPLLanalytic$YPLLdif, p = .75, list = FALSE)
training = YPLLanalytic[ inTraining,]
testing  = YPLLanalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid1 = expand.grid(nrounds = c(25, 50, 100, 200), #200, 300
                       max_depth = c(1, 2, 3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.05),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1 )) #0.9, 1

xgbFit1 = train(YPLLdif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid1,
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit1)) # a very messy plot
vi=varImp(xgbFit1) # much better in a list
vi$importance
xgbFit1
plot(xgbFit1)
```

```{r}
xgb.pdp = list()
res.partialplot = list()
predvarls = list("obesitya", "unemploymenta", "somecollegea", "inactivityb", "childpovertya", "highschoolb", "inactivitya", "childpovertyb", "highschoola", "somecollegeb")
summary(YPLLanalytic$YPLLdif)

for (m in 1:length(predvarls)){
xgb.pdp[[m]] = 
  partial(
    object = xgbFit1,
    pred.var = predvarls[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot[[m]] = plotPartial(xgb.pdp[[m]], rug =TRUE, train = training)
}
for (i in 1:10){
  res.partialplot[[i]]
}
```

# mental
```{r}
library(caret)
library(xgboost)
library(plyr)
library(doParallel)
library(pdp)
rm(list = ls())
set.seed (1)
load("analytic3.RData")
mentalanalytic=analytic3[-c(1,3,4)]
nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(mentalanalytic$mentaldif, p = .75, list = FALSE)
training = mentalanalytic[ inTraining,]
testing  = mentalanalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid2 = expand.grid(nrounds = c(25, 50, 100, 200), #200, 300
                       max_depth = c(1, 2, 3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.05),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1 )) #0.9, 1

xgbFit2 = train(mentaldif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid2,
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit2)) # a very messy plot
vi=varImp(xgbFit2) # much better in a list
vi$importance
xgbFit2
plot(xgbFit2)
```

```{r}
xgb.pdp2 = list()
res.partialplot2 = list()
predvarls2 = list("obesitya", "unemploymenta", "somecollegea", "inactivityb", "childpovertya", "highschoolb", "inactivitya", "childpovertyb", "highschoola", "somecollegeb")
summary(mentalanalytic$mentaldif)

for (m in 1:length(predvarls2)){
xgb.pdp2[[m]] = 
  partial(
    object = xgbFit2,
    pred.var = predvarls2[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot2[[m]] = plotPartial(xgb.pdp2[[m]], rug =TRUE, train = training)
}

for (i in 1:10){
  res.partialplot2[[i]]
}
```

# physical
```{r}
library(caret)
library(xgboost)
library(plyr)
library(doParallel)
library(pdp)
rm(list = ls())
set.seed (1)
load("analytic3.RData")
physicalanalytic=analytic3[-c(1,2,4)]
nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(physicalanalytic$physicaldif, p = .75, list = FALSE)
training = physicalanalytic[ inTraining,]
testing  = physicalanalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid3 = expand.grid(nrounds = c(25, 50, 100, 200), #200, 300
                       max_depth = c(1, 2, 3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.05),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1 )) #0.9, 1

xgbFit3 = train(physicaldif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid3,
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit3)) # a very messy plot
vi=varImp(xgbFit3) # much better in a list
vi$importance
xgbFit3
plot(xgbFit3)
```

```{r}
xgb.pdp3 = list()
res.partialplot3 = list()
predvarls3 = list("obesitya", "unemploymenta", "somecollegea", "inactivityb", "childpovertya", "highschoolb", "inactivitya", "childpovertyb", "highschoola", "somecollegeb")
summary(physicalanalytic$physicaldif)

for (m in 1:length(predvarls3)){
xgb.pdp3[[m]] = 
  partial(
    object = xgbFit3,
    pred.var = predvarls3[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot3[[m]] = plotPartial(xgb.pdp3[[m]], rug =TRUE, train = training)
}

for (i in 1:10){
  res.partialplot3[[i]]
}
```

# fairpoor
```{r}
library(caret)
library(xgboost)
library(plyr)
library(doParallel)
library(pdp)
rm(list = ls())
set.seed (1)
load("analytic3.RData")
fairpooranalytic=analytic3[-c(1,2,3)]
nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(fairpooranalytic$fairpoordif, p = .75, list = FALSE)
training = fairpooranalytic[ inTraining,]
testing  = fairpooranalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid4 = expand.grid(nrounds = c(25, 50, 100, 200), #200, 300
                       max_depth = c(1, 2, 3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.05),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1 )) #0.9, 1

xgbFit4 = train(mentaldif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid4,
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit4)) # a very messy plot
vi=varImp(xgbFit4) # much better in a list
vi$importance
xgbFit4
plot(xgbFit4)
```

```{r}
xgb.pdp4 = list()
res.partialplot4 = list()
predvarls4 = list("obesitya", "unemploymenta", "somecollegea", "inactivityb", "childpovertya", "highschoolb", "inactivitya", "childpovertyb", "highschoola", "somecollegeb")
summary(fairpooranalytic$fairpoordif)

for (m in 1:length(predvarls4)){
xgb.pdp4[[m]] = 
  partial(
    object = xgbFit4,
    pred.var = predvarls4[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot4[[m]] = plotPartial(xgb.pdp4[[m]], rug =TRUE, train = training)
}

for (i in 1:10){
  res.partialplot4[[i]]
}
```