---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(naniar)
rm(list = ls())
set.seed (1)
load("analytic2.RData")

names(analytic2)
analyticb=data.frame(analytic2[1])


# YPLL
YPLLanalytic=data.frame(analytic2[1], analytic2[54:58])
YPLLanalytic=YPLLanalytic %>% pivot_longer(c("YPLLRate_2015", "YPLLRate_2016", "YPLLRate_2017", "YPLLRate_2018", "YPLLRate_2019"), names_to = "year", values_to = "value")
YPLLanalytic=YPLLanalytic %>% 
  mutate( year = case_when(
  year=="YPLLRate_2015" ~ 1,
  year=="YPLLRate_2016" ~ 2,
  year=="YPLLRate_2017" ~ 3,
  year=="YPLLRate_2018" ~ 4,
  year=="YPLLRate_2019" ~ 5,
  TRUE ~ as.numeric(year)
))
pct_miss(YPLLanalytic)
analyticb=analyticb %>% mutate(YPLLb=NA)
for (row in 1:nrow(analyticb)){
  county = YPLLanalytic %>% filter(YPLLanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "YPLLb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# FairPoor
FairPooranalytic=data.frame(analytic2[1], analytic2[66:70])
FairPooranalytic=FairPooranalytic %>% pivot_longer(c("FairPoor_2015", "FairPoor_2016", "FairPoor_2017", "FairPoor_2018", "FairPoor_2019"), names_to = "year", values_to = "value")
FairPooranalytic=FairPooranalytic %>% 
  mutate( year = case_when(
  year=="FairPoor_2015" ~ 1,
  year=="FairPoor_2016" ~ 2,
  year=="FairPoor_2017" ~ 3,
  year=="FairPoor_2018" ~ 4,
  year=="FairPoor_2019" ~ 5,
  TRUE ~ as.numeric(year)
))
pct_miss(FairPooranalytic)
analyticb=analyticb %>% mutate(fairpoorb=NA)
for (row in 1:nrow(analyticb)){
  county = FairPooranalytic %>% filter(FairPooranalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "fairpoorb"]=res.lm$coefficients["county$year"]
}
names(analyticb)


# PhysicallyUnhealthyDays
PhysicallyUnhealthyDaysanalytic=data.frame(analytic2[1], analytic2[78:82])
PhysicallyUnhealthyDaysanalytic=PhysicallyUnhealthyDaysanalytic %>% pivot_longer(c("PhysicallyUnhealthyDays_2015", "PhysicallyUnhealthyDays_2016", "PhysicallyUnhealthyDays_2017", "PhysicallyUnhealthyDays_2018", "PhysicallyUnhealthyDays_2019"), names_to = "year", values_to = "value")
PhysicallyUnhealthyDaysanalytic=PhysicallyUnhealthyDaysanalytic %>% 
  mutate( year = case_when(
  year=="PhysicallyUnhealthyDays_2015" ~ 1,
  year=="PhysicallyUnhealthyDays_2016" ~ 2,
  year=="PhysicallyUnhealthyDays_2017" ~ 3,
  year=="PhysicallyUnhealthyDays_2018" ~ 4,
  year=="PhysicallyUnhealthyDays_2019" ~ 5,
  TRUE ~ as.numeric(year)
))
pct_miss(PhysicallyUnhealthyDaysanalytic)
analyticb=analyticb %>% mutate(physicalb=NA)
for (row in 1:nrow(analyticb)){
  county = PhysicallyUnhealthyDaysanalytic %>% filter(PhysicallyUnhealthyDaysanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "physicalb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# MentallyUnhealthyDays
MentallyUnhealthyDaysanalytic=data.frame(analytic2[1], analytic2[90:94])
MentallyUnhealthyDaysanalytic=MentallyUnhealthyDaysanalytic %>% pivot_longer(c("MentallyUnhealthyDays_2015", "MentallyUnhealthyDays_2016", "MentallyUnhealthyDays_2017", "MentallyUnhealthyDays_2018", "MentallyUnhealthyDays_2019"), names_to = "year", values_to = "value")
MentallyUnhealthyDaysanalytic=MentallyUnhealthyDaysanalytic %>% 
  mutate( year = case_when(
  year=="MentallyUnhealthyDays_2015" ~ 1,
  year=="MentallyUnhealthyDays_2016" ~ 2,
  year=="MentallyUnhealthyDays_2017" ~ 3,
  year=="MentallyUnhealthyDays_2018" ~ 4,
  year=="MentallyUnhealthyDays_2019" ~ 5,
  TRUE ~ as.numeric(year)
))
pct_miss(MentallyUnhealthyDaysanalytic)
analyticb=analyticb %>% mutate(mentalb=NA)
for (row in 1:nrow(analyticb)){
  county = MentallyUnhealthyDaysanalytic %>% filter(MentallyUnhealthyDaysanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "mentalb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# unemployment
unemploymentanalytic=data.frame(analytic2[1], analytic2[10:14])
unemploymentanalytic=unemploymentanalytic %>% pivot_longer(c("unemploymentrate_2010", "unemploymentrate_2011", "unemploymentrate_2012", "unemploymentrate_2013", "unemploymentrate_2014"), names_to = "year", values_to = "value")
unemploymentanalytic=unemploymentanalytic %>% 
  mutate( year = case_when(
  year=="unemploymentrate_2010" ~ 1,
  year=="unemploymentrate_2011" ~ 2,
  year=="unemploymentrate_2012" ~ 3,
  year=="unemploymentrate_2013" ~ 4,
  year=="unemploymentrate_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(unemploymentanalytic)
analyticb=analyticb %>% mutate(unemploymenta=NA, unemploymentb=NA)
for (row in 1:nrow(analyticb)){
  county = unemploymentanalytic %>% filter(unemploymentanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "unemploymenta"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "unemploymentb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# uninsured
uninsuredanalytic=data.frame(analytic2[1], analytic2[22:26])
uninsuredanalytic=uninsuredanalytic %>% pivot_longer(c("uninsuredrate_2010", "uninsuredrate_2011", "uninsuredrate_2012", "uninsuredrate_2013", "uninsuredrate_2014"), names_to = "year", values_to = "value")
uninsuredanalytic=uninsuredanalytic %>% 
  mutate( year = case_when(
  year=="uninsuredrate_2010" ~ 1,
  year=="uninsuredrate_2011" ~ 2,
  year=="uninsuredrate_2012" ~ 3,
  year=="uninsuredrate_2013" ~ 4,
  year=="uninsuredrate_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(uninsuredanalytic)
analyticb=analyticb %>% mutate(uninsureda=NA, uninsuredb=NA)
for (row in 1:nrow(analyticb)){
  county = uninsuredanalytic %>% filter(uninsuredanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "uninsureda"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "uninsuredb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# childpoverty
childpovertyanalytic=data.frame(analytic2[1], analytic2[39:43])
childpovertyanalytic=childpovertyanalytic %>% pivot_longer(c("childpoverty_2010", "childpoverty_2011", "childpoverty_2012", "childpoverty_2013", "childpoverty_2014"), names_to = "year", values_to = "value")
childpovertyanalytic=childpovertyanalytic %>% 
  mutate( year = case_when(
  year=="childpoverty_2010" ~ 1,
  year=="childpoverty_2011" ~ 2,
  year=="childpoverty_2012" ~ 3,
  year=="childpoverty_2013" ~ 4,
  year=="childpoverty_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(childpovertyanalytic)
analyticb=analyticb %>% mutate(childpovertya=NA, childpovertyb=NA)
for (row in 1:nrow(analyticb)){
  county = childpovertyanalytic %>% filter(childpovertyanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "childpovertya"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "childpovertyb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# PCPRate
pcpanalytic=data.frame(analytic2[1], analytic2[97:100])
pcpanalytic=pcpanalytic %>% pivot_longer(c("PCPRate_2010", "PCPRate_2011", "PCPRate_2013", "PCPRate_2014"), names_to = "year", values_to = "value")
pcpanalytic=pcpanalytic %>% 
  mutate( year = case_when(
  year=="PCPRate_2010" ~ 1,
  year=="PCPRate_2011" ~ 2,
  year=="PCPRate_2012" ~ 3,
  year=="PCPRate_2013" ~ 4,
  year=="PCPRate_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(pcpanalytic)
analyticb=analyticb %>% mutate(PCPRatea=NA, PCPRateb=NA)
for (row in 1:nrow(analyticb)){
  county = pcpanalytic %>% filter(pcpanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "PCPRatea"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "PCPRateb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# obesity
obesityanalytic=data.frame(analytic2[1], analytic2[108:111])
obesityanalytic=obesityanalytic %>% pivot_longer(c("obesity_2010", "obesity_2011", "obesity_2012", "obesity_2014"), names_to = "year", values_to = "value")
obesityanalytic=obesityanalytic %>% 
  mutate( year = case_when(
  year=="obesity_2010" ~ 1,
  year=="obesity_2011" ~ 2,
  year=="obesity_2012" ~ 3,
  year=="obesity_2013" ~ 4,
  year=="obesity_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(obesityanalytic)
analyticb=analyticb %>% mutate(obesitya=NA, obesityb=NA)
for (row in 1:nrow(analyticb)){
  county = obesityanalytic %>% filter(obesityanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "obesitya"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "obesityb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# inactivity
inactivityanalytic=data.frame(analytic2[1], analytic2[124:126])
inactivityanalytic=inactivityanalytic %>% pivot_longer(c("inactivity_2011", "inactivity_2012", "inactivity_2014"), names_to = "year", values_to = "value")
inactivityanalytic=inactivityanalytic %>% 
  mutate( year = case_when(
  year=="inactivity_2010" ~ 1,
  year=="inactivity_2011" ~ 2,
  year=="inactivity_2012" ~ 3,
  year=="inactivity_2013" ~ 4,
  year=="inactivity_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(inactivityanalytic)
analyticb=analyticb %>% mutate(inactivitya=NA, inactivityb=NA)
for (row in 1:nrow(analyticb)){
  county = inactivityanalytic %>% filter(inactivityanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "inactivitya"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "inactivityb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# somecollege
somecollegeanalytic=data.frame(analytic2[1], analytic2[134:138])
somecollegeanalytic=somecollegeanalytic %>% pivot_longer(c("somecollege_2010", "somecollege_2011", "somecollege_2012", "somecollege_2013", "somecollege_2014"), names_to = "year", values_to = "value")
somecollegeanalytic=somecollegeanalytic %>% 
  mutate( year = case_when(
  year=="somecollege_2010" ~ 1,
  year=="somecollege_2011" ~ 2,
  year=="somecollege_2012" ~ 3,
  year=="somecollege_2013" ~ 4,
  year=="somecollege_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(somecollegeanalytic)
analyticb=analyticb %>% mutate(somecollegea=NA, somecollegeb=NA)
for (row in 1:nrow(analyticb)){
  county = somecollegeanalytic %>% filter(somecollegeanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "somecollegea"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "somecollegeb"]=res.lm$coefficients["county$year"]
}
names(analyticb)

# highschool
highschoolanalytic=data.frame(analytic2[1], analytic2[146:150])
highschoolanalytic=highschoolanalytic %>% pivot_longer(c("highschool_2010", "highschool_2011", "highschool_2012", "highschool_2013", "highschool_2014"), names_to = "year", values_to = "value")
highschoolanalytic=highschoolanalytic %>% 
  mutate( year = case_when(
  year=="highschool_2010" ~ 1,
  year=="highschool_2011" ~ 2,
  year=="highschool_2012" ~ 3,
  year=="highschool_2013" ~ 4,
  year=="highschool_2014" ~ 5,
  TRUE ~ as.numeric(year)
))
# the console give "Warning: NAs introduced by coercion" but actually no NA???
pct_miss(highschoolanalytic)
analyticb=analyticb %>% mutate(highschoola=NA, highschoolb=NA)
for (row in 1:nrow(analyticb)){
  county = highschoolanalytic %>% filter(highschoolanalytic$FIPS == analyticb[row, "FIPS"]) 
  res.lm = lm(county$value ~ county$year, data=county)
  analyticb[row, "highschoola"]=res.lm$coefficients["(Intercept)"]
  analyticb[row, "highschoolb"]=res.lm$coefficients["county$year"]
}
names(analyticb)
save(analyticb, file = "analyticbFIPS.RData")
analyticb=analyticb[-c(1)]
names(analyticb)
save(analyticb, file = "analyticb.RData")
```

```{r}
rm(list = ls())
load("weight.RData")
load("analyticbFIPS.RData")
analyticnweight=merge(weight, analyticb,  by.x="FIPS", by.y="FIPS")
analyticnweight=analyticnweight[-c(1)]

library(tidyverse)
library(readxl)
library(corrplot)
library(weights)
rm(list = ls())
disparity=read_csv("./race.csv", col_types = "ccdddd")
disparity$FIPS=substr(disparity$GEO_ID, 10, 14)
disparity$blwt=disparity$S1701_C03_010E - disparity$S1701_C03_009E
disparity$hpnon=disparity$S1701_C03_016E - disparity$S1701_C03_017E
tomerge=disparity[c(7:9)]
load("analytic3FIPS.RData")
analyticwrace=merge(analytic3, tomerge, by.x="FIPS", by.y="FIPS")
load("weight.RData")
analyticwrace=merge(analyticwrace, weight, by.x="FIPS", by.y="FIPS")
analyticwrace = na.omit(analyticwrace)
analyticwrace = analyticwrace[-1]

```

# YPLL

```{r}
options(width = 300)
matrix(runif(100), ncol = 20)

library(caret)
library(xgboost)
library(doParallel)
library(pdp)
set.seed (1)
YPLLanalytic=analyticwrace[-c(2,3,4,23)]


nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel


inTraining = createDataPartition(YPLLanalytic$YPLLdif, p = .75, list = FALSE)
training = YPLLanalytic[ inTraining,]
testing  = YPLLanalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid1 = expand.grid(nrounds = c(50, 100, 200), #200, 300
                       max_depth = c(1, 2, 3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.05),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1 )) #0.9, 1

xgbFit1 = train(YPLLdif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid1,
                weights = analyticwrace$averweight[inTraining],
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit1))
vi=varImp(xgbFit1)
vi$importance
xgbFit1
plot(xgbFit1)
```

```{r }
xgb.pdp = list()
res.partialplot = list()
predvarls = list("somecollegea", "obesitya", "inactivitya", "uninsureda",  "unemploymenta", "blwt", "highschoola", "inactivityb", "obesityb", "highschoolb")
summary(YPLLanalytic$YPLLdif)

for (m in 1:length(predvarls)){
xgb.pdp[[m]] = 
  partial(
    object = xgbFit1,
    pred.var = predvarls[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot[[m]] = plotPartial(xgb.pdp[[m]], rug =TRUE, train = training ) #, ylim=c(99, 601)
}

res.partialplot[[1]]
res.partialplot[[2]]
res.partialplot[[3]]
res.partialplot[[4]]
res.partialplot[[5]]
res.partialplot[[6]]
res.partialplot[[7]]
res.partialplot[[8]]
res.partialplot[[9]]
res.partialplot[[10]]
```

# mental
```{r}
options(width = 300)
matrix(runif(100), ncol = 20)

library(caret)
library(xgboost)
library(doParallel)
library(pdp)
set.seed (1)
mentalanalytic=analyticwrace[-c(1,3,4,23)]
nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(mentalanalytic$mentaldif, p = .75, list = FALSE)
training = mentalanalytic[ inTraining,]
testing  = mentalanalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid2 = expand.grid(nrounds = c(50, 100, 200), #200, 300
                       max_depth =c(1,2,3), #2, 4, 6
                       eta = c(0.01, 0.025),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8,0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c( 0.8, 0.9, 1 )) #0.9, 1

xgbFit2 = train(mentaldif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid2,
                weights = analyticwrace$averweight[inTraining],
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit2)) 
vi=varImp(xgbFit2)
vi$importance
xgbFit2
plot(xgbFit2)
```

```{r }
xgb.pdp2 = list()
res.partialplot2 = list()
predvarls2 = list("unemploymenta", "highschoolb", "obesitya", "inactivitya", "unemploymentb", "somecollegeb", "hpnon", "blwt", "uninsuredb", "uninsureda")
summary(mentalanalytic$mentaldif)

for (m in 1:length(predvarls2)){
xgb.pdp2[[m]] = 
  partial(
    object = xgbFit2,
    pred.var = predvarls2[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot2[[m]] = plotPartial(xgb.pdp2[[m]], rug =TRUE, train = training) #, ylim=c(0.09,0.61)
}

res.partialplot2[[1]]
res.partialplot2[[2]]
res.partialplot2[[3]]
res.partialplot2[[4]]
res.partialplot2[[5]]
res.partialplot2[[6]]
res.partialplot2[[7]]
res.partialplot2[[8]]
res.partialplot2[[9]]
res.partialplot2[[10]]
```

# physical
```{r}
options(width = 300)
matrix(runif(100), ncol = 20)

library(caret)
library(xgboost)
library(doParallel)
library(pdp)
set.seed (1)
physicalanalytic=analyticwrace[-c(1,2,4,23)]

nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(physicalanalytic$physicaldif, p = .75, list = FALSE)
training = physicalanalytic[ inTraining,]
testing  = physicalanalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid3 = expand.grid(nrounds = c(50, 100, 200), #200, 300
                       max_depth = c(1,2,3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.05),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c( 0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1)) #0.9, 1

xgbFit3 = train(physicaldif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid3,
                weights = analyticwrace$averweight[inTraining],
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit3)) 
vi=varImp(xgbFit3) 
vi$importance
xgbFit3
plot(xgbFit3)
```

```{r }
xgb.pdp3 = list()
res.partialplot3 = list()
predvarls3 = list("somecollegea", "blwt", "inactivitya", "uninsureda", "childpovertya", "highschoolb", "obesityb", "highschoola", "hpnon", "unemploymenta")
summary(physicalanalytic$physicaldif)

for (m in 1:length(predvarls3)){
xgb.pdp3[[m]] = 
  partial(
    object = xgbFit3,
    pred.var = predvarls3[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot3[[m]] = plotPartial(xgb.pdp3[[m]], rug =TRUE, train = training) #, ylim=c(-0.35, 0.45)
}

res.partialplot3[[1]]
res.partialplot3[[2]]
res.partialplot3[[3]]
res.partialplot3[[4]]
res.partialplot3[[5]]
res.partialplot3[[6]]
res.partialplot3[[7]]
res.partialplot3[[8]]
res.partialplot3[[9]]
res.partialplot3[[10]]
```

# fairpoor
```{r}
options(width = 300)
matrix(runif(100), ncol = 20)

library(caret)
library(xgboost)
library(doParallel)
library(pdp)
set.seed (1)
fairpooranalytic=analyticwrace[-c(1,2,3,23)]
nc = parallel::detectCores()  
cl = makePSOCKcluster(nc-1)   # Set number of cores equal to machine number minus one
registerDoParallel(cl)        #Set up parallel

inTraining = createDataPartition(fairpooranalytic$fairpoordif, p = .75, list = FALSE)
training = fairpooranalytic[ inTraining,]
testing  = fairpooranalytic[-inTraining,]
fitControl = trainControl(method = "repeatedcv",
                           number = 10,
                           repeats = 10,
                          allowParallel=TRUE
                          )

xgbGrid4 = expand.grid(nrounds = c(50, 100, 200), #200, 300
                       max_depth = c(1,2,3), #2, 4, 6
                       eta = c(0.01, 0.025, 0.5),  # 0.05, 0.075
                       gamma = 0,
                       colsample_bytree = c(0.8, 0.9, 1), #6, 7, 8
                       min_child_weight = 20,
                       subsample = c(0.8, 0.9, 1 )) #0.9, 1

xgbFit4 = train(fairpoordif ~ ., data = training,
                 method = "xgbTree", 
                 trControl = fitControl,
                 tuneGrid = xgbGrid4,
                weights = analyticwrace$averweight[inTraining],
                nthread=1,
                verbosity = 0
                )

stopCluster(cl)
plot(varImp(xgbFit4))
vi=varImp(xgbFit4)
vi$importance
xgbFit4
plot(xgbFit4)
```

```{r }
xgb.pdp4 = list()
res.partialplot4 = list()
predvarls4 = list("somecollegea", "inactivitya", "childpovertya", "uninsureda", "unemploymenta", "unemploymentb", "childpovertyb", "blwt", "inactivityb", "obesityb")
summary(fairpooranalytic$fairpoordif)

for (m in 1:length(predvarls4)){
xgb.pdp4[[m]] = 
  partial(
    object = xgbFit4,
    pred.var = predvarls4[[m]],
    plot = FALSE,
    chull = TRUE,
    plot.engine = "ggplot2"
  )
res.partialplot4[[m]] = plotPartial(xgb.pdp4[[m]], rug =TRUE, train = training ) #, ylim=c(-2.5,3.1)
}

res.partialplot4[[1]]
res.partialplot4[[2]]
res.partialplot4[[3]]
res.partialplot4[[4]]
res.partialplot4[[5]]
res.partialplot4[[6]]
res.partialplot4[[7]]
res.partialplot4[[8]]
res.partialplot4[[9]]
res.partialplot4[[10]]
```